[build]
  command = "npm run build" # Команда сборки вашего проекта (если требуется)
  functions = "netlify" # Путь к папке с функциями Netlify

[dev]
  functions = "netlify" # Путь к папке с функциями Netlify